// Global using
global using Microsoft.EntityFrameworkCore;
global using SubastaYa.API;
global using SubastaYa.API.Hubs;
global using SubastaYa.API.Middleware;
global using SubastaYa.API.Services;
// Interface
global using SubastaYa.Application.Interfaces;
global using SubastaYa.Application.Interfaces.Repositories;
global using SubastaYa.Application.Interfaces.Security;
global using SubastaYa.Application.Interfaces.Service.Auctions;
global using SubastaYa.Application.Interfaces.Service.Audits;
global using SubastaYa.Application.Interfaces.Service.Bids;
global using SubastaYa.Application.Interfaces.Service.Categories;
global using SubastaYa.Application.Interfaces.Service.LedgerTransactions;
global using SubastaYa.Application.Interfaces.Service.Users;
global using SubastaYa.Application.Interfaces.Service.Wallets;
global using SubastaYa.Application.Interfaces.Service.Worker;
// Use case
global using SubastaYa.Application.UseCases.Auctions.CreateAuction;
global using SubastaYa.Application.UseCases.Auctions.GetAuction;
global using SubastaYa.Application.UseCases.Auctions.GetAuctions;
global using SubastaYa.Application.UseCases.Audits.GetAudit;
global using SubastaYa.Application.UseCases.Audits.GetAudits;
global using SubastaYa.Application.UseCases.Bids.CreateBid;
global using SubastaYa.Application.UseCases.Categories.CreateCategory;
global using SubastaYa.Application.UseCases.Categories.GetCategories;
global using SubastaYa.Application.UseCases.LedgerTransactions.GetTransaction;
global using SubastaYa.Application.UseCases.LedgerTransactions.GetTransactions;
global using SubastaYa.Application.UseCases.Users.CreateUser;
global using SubastaYa.Application.UseCases.Users.GetUser;
global using SubastaYa.Application.UseCases.Users.GetMyAuctions;
global using SubastaYa.Application.UseCases.Users.UserAuthentication;
global using SubastaYa.Application.UseCases.Wallets.BalanceWallet;
global using SubastaYa.Application.UseCases.Wallets.DepositWallet;
global using SubastaYa.Application.UseCases.Worker;
// Infrastructure
global using SubastaYa.Infrastructure.Persistence;
global using SubastaYa.Infrastructure.Persistence.Repositories;
global using SubastaYa.Infrastructure.Security;
global using SubastaYa.Infrastructure.Workers;